spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

config:
    activate:
      on-profile: test
name: test-YAML
environment: testing

enabled: true

h2:
  console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

